In [1]:
pwd

'/content'

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import pandas as pd
import plotly.express as pr
import plotly.graph_objects as go

In [4]:
import pandas as pd

In [6]:
df = pd.read_csv('/content/drive/MyDrive/airline_data.csv')
df

,Unnamed: 0,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,...,Div4WheelsOff,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum
0,1295781,1998,2,4,2,4,1998-04-02,AS,19930,AS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1125375,2013,2,5,13,1,2013-05-13,EV,20366,EV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,118824,1993,3,9,25,6,1993-09-25,UA,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,634825,1994,4,11,12,6,1994-11-12,HP,19991,HP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1888125,2017,3,8,17,4,2017-08-17,UA,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26995,821542,2017,1,1,24,2,2017-01-24,DL,19790,DL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26996,1910565,2013,2,6,27,4,2013-06-27,B6,20409,B6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26997,9055,2016,3,8,26,5,2016-08-26,AA,19805,AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26998,84136,2009,3,8,8,6,2009-08-08,YV,20378,YV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26999,113029,1993,3,7,17,6,1993-07-17,DL,19790,DL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.shape

(27000, 110)

In [8]:
df.info

<bound method DataFrame.info of        Unnamed: 0  Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
0         1295781  1998        2      4           2          4  1998-04-02
1         1125375  2013        2      5          13          1  2013-05-13
2          118824  1993        3      9          25          6  1993-09-25
3          634825  1994        4     11          12          6  1994-11-12
4         1888125  2017        3      8          17          4  2017-08-17
...           ...   ...      ...    ...         ...        ...         ...
26995      821542  2017        1      1          24          2  2017-01-24
26996     1910565  2013        2      6          27          4  2013-06-27
26997        9055  2016        3      8          26          5  2016-08-26
26998       84136  2009        3      8           8          6  2009-08-08
26999      113029  1993        3      7          17          6  1993-07-17

      Reporting_Airline  DOT_ID_Reporting_Airline IATA_CODE_Reporting_Airline  \
0                    AS                     19930                          AS
1                    EV                     20366                          EV
2                    UA                     19977                          UA
3                    HP                     19991                          HP
4                    UA                     19977                          UA
...                 ...                       ...                         ...
26995                DL                     19790                          DL
26996                B6                     20409                          B6
26997                AA                     19805                          AA
26998                YV                     20378                          YV
26999                DL                     19790                          DL

       ... Div4WheelsOff  Div4TailNum  Div5Airport  Div5AirportID  \
0      ...           NaN          NaN          NaN            NaN
1      ...           NaN          NaN          NaN            NaN
2      ...           NaN          NaN          NaN            NaN
3      ...           NaN          NaN          NaN            NaN
4      ...           NaN          NaN          NaN            NaN
...    ...           ...          ...          ...            ...
26995  ...           NaN          NaN          NaN            NaN
26996  ...           NaN          NaN          NaN            NaN
26997  ...           NaN          NaN          NaN            NaN
26998  ...           NaN          NaN          NaN            NaN
26999  ...           NaN          NaN          NaN            NaN

       Div5AirportSeqID Div5WheelsOn Div5TotalGTime Div5LongestGTime  \
0                   NaN          NaN            NaN              NaN
1                   NaN          NaN            NaN              NaN
2                   NaN          NaN            NaN              NaN
3                   NaN          NaN            NaN              NaN
4                   NaN          NaN            NaN              NaN
...                 ...          ...            ...              ...
26995               NaN          NaN            NaN              NaN
26996               NaN          NaN            NaN              NaN
26997               NaN          NaN            NaN              NaN
26998               NaN          NaN            NaN              NaN
26999               NaN          NaN            NaN              NaN

       Div5WheelsOff Div5TailNum
0                NaN         NaN
1                NaN         NaN
2                NaN         NaN
3                NaN         NaN
4                NaN         NaN
...              ...         ...
26995            NaN         NaN
26996            NaN         NaN
26997            NaN         NaN
26998            NaN         NaN
26999            NaN         NaN

[27000 rows x 110 columns]>

In [9]:
df.isna().sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of        Unnamed: 0   Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
0           False  False    False  False       False      False       False
1           False  False    False  False       False      False       False
2           False  False    False  False       False      False       False
3           False  False    False  False       False      False       False
4           False  False    False  False       False      False       False
...           ...    ...      ...    ...         ...        ...         ...
26995       False  False    False  False       False      False       False
26996       False  False    False  False       False      False       False
26997       False  False    False  False       False      False       False
26998       False  False    False  False       False      False       False
26999       False  False    False  False       False      False       False

       Reporting_Airline  DOT_ID_Reporting_Airline  \
0                  False                     False
1                  False                     False
2                  False                     False
3                  False                     False
4                  False                     False
...                  ...                       ...
26995              False                     False
26996              False                     False
26997              False                     False
26998              False                     False
26999              False                     False

       IATA_CODE_Reporting_Airline  ...  Div4WheelsOff  Div4TailNum  \
0                            False  ...           True         True
1                            False  ...           True         True
2                            False  ...           True         True
3                            False  ...           True         True
4                            False  ...           True         True
...                            ...  ...            ...          ...
26995                        False  ...           True         True
26996                        False  ...           True         True
26997                        False  ...           True         True
26998                        False  ...           True         True
26999                        False  ...           True         True

       Div5Airport  Div5AirportID  Div5AirportSeqID  Div5WheelsOn  \
0             True           True              True          True
1             True           True              True          True
2             True           True              True          True
3             True           True              True          True
4             True           True              True          True
...            ...            ...               ...           ...
26995         True           True              True          True
26996         True           True              True          True
26997         True           True              True          True
26998         True           True              True          True
26999         True           True              True          True

       Div5TotalGTime  Div5LongestGTime  Div5WheelsOff  Div5TailNum
0                True              True           True         True
1                True              True           True         True
2                True              True           True         True
3                True              True           True         True
4                True              True           True         True
...               ...               ...            ...          ...
26995            True              True           True         True
26996            True              True           True         True
26997            True              True           True         True
26998            True              True           True         True
26999            True              True           True         True

[27000 rows x 110 columns]>

In [12]:
df.dropna(axis=1, inplace=True)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27000 entries, 0 to 26999
Data columns (total 32 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Unnamed: 0                       27000 non-null  int64
 1   Year                             27000 non-null  int64
 2   Quarter                          27000 non-null  int64
 3   Month                            27000 non-null  int64
 4   DayofMonth                       27000 non-null  int64
 5   DayOfWeek                        27000 non-null  int64
 6   FlightDate                       27000 non-null  object
 7   Reporting_Airline                27000 non-null  object
 8   DOT_ID_Reporting_Airline         27000 non-null  int64
 9   IATA_CODE_Reporting_Airline      27000 non-null  object
 10  Flight_Number_Reporting_Airline  27000 non-null  int64
 11  OriginAirportID                  27000 non-null  int64
 12  OriginAirportSeqID               27000 non-null  int64
 13  OriginCityMarketID               27000 non-null  int64
 14  Origin                           27000 non-null  object
 15  OriginCityName                   27000 non-null  object
 16  OriginWac                        27000 non-null  int64
 17  DestAirportID                    27000 non-null  int64
 18  DestAirportSeqID                 27000 non-null  int64
 19  DestCityMarketID                 27000 non-null  int64
 20  Dest                             27000 non-null  object
 21  DestCityName                     27000 non-null  object
 22  DestWac                          27000 non-null  int64
 23  CRSDepTime                       27000 non-null  int64
 24  DepTimeBlk                       27000 non-null  object
 25  CRSArrTime                       27000 non-null  int64
 26  ArrTimeBlk                       27000 non-null  object
 27  Cancelled                        27000 non-null  float64
 28  Diverted                         27000 non-null  float64
 29  Flights                          27000 non-null  float64
 30  Distance                         27000 non-null  float64
 31  DistanceGroup                    27000 non-null  int64
dtypes: float64(4), int64(19), object(9)
memory usage: 6.6+ MB

In [14]:
df.describe

<bound method NDFrame.describe of        Unnamed: 0  Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
0         1295781  1998        2      4           2          4  1998-04-02
1         1125375  2013        2      5          13          1  2013-05-13
2          118824  1993        3      9          25          6  1993-09-25
3          634825  1994        4     11          12          6  1994-11-12
4         1888125  2017        3      8          17          4  2017-08-17
...           ...   ...      ...    ...         ...        ...         ...
26995      821542  2017        1      1          24          2  2017-01-24
26996     1910565  2013        2      6          27          4  2013-06-27
26997        9055  2016        3      8          26          5  2016-08-26
26998       84136  2009        3      8           8          6  2009-08-08
26999      113029  1993        3      7          17          6  1993-07-17

      Reporting_Airline  DOT_ID_Reporting_Airline IATA_CODE_Reporting_Airline  \
0                    AS                     19930                          AS
1                    EV                     20366                          EV
2                    UA                     19977                          UA
3                    HP                     19991                          HP
4                    UA                     19977                          UA
...                 ...                       ...                         ...
26995                DL                     19790                          DL
26996                B6                     20409                          B6
26997                AA                     19805                          AA
26998                YV                     20378                          YV
26999                DL                     19790                          DL

       ...  DestWac  CRSDepTime  DepTimeBlk  CRSArrTime ArrTimeBlk Cancelled  \
0      ...       93        1330   1300-1359        1426  1400-1459       0.0
1      ...       38        1301   1300-1359        1423  1400-1459       0.0
2      ...       41        1650   1600-1659        1730  1700-1759       0.0
3      ...       81        1245   1200-1259        1457  1400-1459       0.0
4      ...       82         755   0700-0759         902  0900-0959       0.0
...    ...      ...         ...         ...         ...        ...       ...
26995  ...       63         910   0900-0959        1028  1000-1059       0.0
26996  ...       74        1320   1300-1359        1612  1600-1659       0.0
26997  ...       22         920   0900-0959        1405  1400-1459       0.0
26998  ...       82        1139   1100-1159        1217  1200-1259       0.0
26999  ...       74         615   0600-0659         721  0700-0759       0.0

       Diverted  Flights  Distance  DistanceGroup
0           0.0      1.0     224.0              1
1           0.0      1.0     277.0              2
2           0.0      1.0     130.0              1
3           0.0      1.0     370.0              2
4           0.0      1.0     692.0              3
...         ...      ...       ...            ...
26995       0.0      1.0     297.0              2
26996       0.0      1.0    1562.0              7
26997       0.0      1.0    1521.0              7
26998       0.0      1.0      73.0              1
26999       0.0      1.0     304.0              2

[27000 rows x 32 columns]>

In [15]:
df.count

<bound method DataFrame.count of        Unnamed: 0  Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
0         1295781  1998        2      4           2          4  1998-04-02
1         1125375  2013        2      5          13          1  2013-05-13
2          118824  1993        3      9          25          6  1993-09-25
3          634825  1994        4     11          12          6  1994-11-12
4         1888125  2017        3      8          17          4  2017-08-17
...           ...   ...      ...    ...         ...        ...         ...
26995      821542  2017        1      1          24          2  2017-01-24
26996     1910565  2013        2      6          27          4  2013-06-27
26997        9055  2016        3      8          26          5  2016-08-26
26998       84136  2009        3      8           8          6  2009-08-08
26999      113029  1993        3      7          17          6  1993-07-17

      Reporting_Airline  DOT_ID_Reporting_Airline IATA_CODE_Reporting_Airline  \
0                    AS                     19930                          AS
1                    EV                     20366                          EV
2                    UA                     19977                          UA
3                    HP                     19991                          HP
4                    UA                     19977                          UA
...                 ...                       ...                         ...
26995                DL                     19790                          DL
26996                B6                     20409                          B6
26997                AA                     19805                          AA
26998                YV                     20378                          YV
26999                DL                     19790                          DL

       ...  DestWac  CRSDepTime  DepTimeBlk  CRSArrTime ArrTimeBlk Cancelled  \
0      ...       93        1330   1300-1359        1426  1400-1459       0.0
1      ...       38        1301   1300-1359        1423  1400-1459       0.0
2      ...       41        1650   1600-1659        1730  1700-1759       0.0
3      ...       81        1245   1200-1259        1457  1400-1459       0.0
4      ...       82         755   0700-0759         902  0900-0959       0.0
...    ...      ...         ...         ...         ...        ...       ...
26995  ...       63         910   0900-0959        1028  1000-1059       0.0
26996  ...       74        1320   1300-1359        1612  1600-1659       0.0
26997  ...       22         920   0900-0959        1405  1400-1459       0.0
26998  ...       82        1139   1100-1159        1217  1200-1259       0.0
26999  ...       74         615   0600-0659         721  0700-0759       0.0

       Diverted  Flights  Distance  DistanceGroup
0           0.0      1.0     224.0              1
1           0.0      1.0     277.0              2
2           0.0      1.0     130.0              1
3           0.0      1.0     370.0              2
4           0.0      1.0     692.0              3
...         ...      ...       ...            ...
26995       0.0      1.0     297.0              2
26996       0.0      1.0    1562.0              7
26997       0.0      1.0    1521.0              7
26998       0.0      1.0      73.0              1
26999       0.0      1.0     304.0              2

[27000 rows x 32 columns]>

In [16]:
df

,Unnamed: 0,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,...,DestWac,CRSDepTime,DepTimeBlk,CRSArrTime,ArrTimeBlk,Cancelled,Diverted,Flights,Distance,DistanceGroup
0,1295781,1998,2,4,2,4,1998-04-02,AS,19930,AS,...,93,1330,1300-1359,1426,1400-1459,0.0,0.0,1.0,224.0,1
1,1125375,2013,2,5,13,1,2013-05-13,EV,20366,EV,...,38,1301,1300-1359,1423,1400-1459,0.0,0.0,1.0,277.0,2
2,118824,1993,3,9,25,6,1993-09-25,UA,19977,UA,...,41,1650,1600-1659,1730,1700-1759,0.0,0.0,1.0,130.0,1
3,634825,1994,4,11,12,6,1994-11-12,HP,19991,HP,...,81,1245,1200-1259,1457,1400-1459,0.0,0.0,1.0,370.0,2
4,1888125,2017,3,8,17,4,2017-08-17,UA,19977,UA,...,82,755,0700-0759,902,0900-0959,0.0,0.0,1.0,692.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26995,821542,2017,1,1,24,2,2017-01-24,DL,19790,DL,...,63,910,0900-0959,1028,1000-1059,0.0,0.0,1.0,297.0,2
26996,1910565,2013,2,6,27,4,2013-06-27,B6,20409,B6,...,74,1320,1300-1359,1612,1600-1659,0.0,0.0,1.0,1562.0,7
26997,9055,2016,3,8,26,5,2016-08-26,AA,19805,AA,...,22,920,0900-0959,1405,1400-1459,0.0,0.0,1.0,1521.0,7
26998,84136,2009,3,8,8,6,2009-08-08,YV,20378,YV,...,82,1139,1100-1159,1217,1200-1259,0.0,0.0,1.0,73.0,1
26999,113029,1993,3,7,17,6,1993-07-17,DL,19790,DL,...,74,615,0600-0659,721,0700-0759,0.0,0.0,1.0,304.0,2

In [20]:
df.drop

<bound method DataFrame.drop of        Unnamed: 0  Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
0         1295781  1998        2      4           2          4  1998-04-02
1         1125375  2013        2      5          13          1  2013-05-13
2          118824  1993        3      9          25          6  1993-09-25
3          634825  1994        4     11          12          6  1994-11-12
4         1888125  2017        3      8          17          4  2017-08-17
...           ...   ...      ...    ...         ...        ...         ...
26995      821542  2017        1      1          24          2  2017-01-24
26996     1910565  2013        2      6          27          4  2013-06-27
26997        9055  2016        3      8          26          5  2016-08-26
26998       84136  2009        3      8           8          6  2009-08-08
26999      113029  1993        3      7          17          6  1993-07-17

      Reporting_Airline  DOT_ID_Reporting_Airline IATA_CODE_Reporting_Airline  \
0                    AS                     19930                          AS
1                    EV                     20366                          EV
2                    UA                     19977                          UA
3                    HP                     19991                          HP
4                    UA                     19977                          UA
...                 ...                       ...                         ...
26995                DL                     19790                          DL
26996                B6                     20409                          B6
26997                AA                     19805                          AA
26998                YV                     20378                          YV
26999                DL                     19790                          DL

       ...  DestWac  CRSDepTime  DepTimeBlk  CRSArrTime ArrTimeBlk Cancelled  \
0      ...       93        1330   1300-1359        1426  1400-1459       0.0
1      ...       38        1301   1300-1359        1423  1400-1459       0.0
2      ...       41        1650   1600-1659        1730  1700-1759       0.0
3      ...       81        1245   1200-1259        1457  1400-1459       0.0
4      ...       82         755   0700-0759         902  0900-0959       0.0
...    ...      ...         ...         ...         ...        ...       ...
26995  ...       63         910   0900-0959        1028  1000-1059       0.0
26996  ...       74        1320   1300-1359        1612  1600-1659       0.0
26997  ...       22         920   0900-0959        1405  1400-1459       0.0
26998  ...       82        1139   1100-1159        1217  1200-1259       0.0
26999  ...       74         615   0600-0659         721  0700-0759       0.0

       Diverted  Flights  Distance  DistanceGroup
0           0.0      1.0     224.0              1
1           0.0      1.0     277.0              2
2           0.0      1.0     130.0              1
3           0.0      1.0     370.0              2
4           0.0      1.0     692.0              3
...         ...      ...       ...            ...
26995       0.0      1.0     297.0              2
26996       0.0      1.0    1562.0              7
26997       0.0      1.0    1521.0              7
26998       0.0      1.0      73.0              1
26999       0.0      1.0     304.0              2

[27000 rows x 32 columns]>

In [21]:
df.isna()

,Unnamed: 0,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,...,DestWac,CRSDepTime,DepTimeBlk,CRSArrTime,ArrTimeBlk,Cancelled,Diverted,Flights,Distance,DistanceGroup
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [23]:
df1 = df.copy()
df1

,Unnamed: 0,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,...,DestWac,CRSDepTime,DepTimeBlk,CRSArrTime,ArrTimeBlk,Cancelled,Diverted,Flights,Distance,DistanceGroup
0,1295781,1998,2,4,2,4,1998-04-02,AS,19930,AS,...,93,1330,1300-1359,1426,1400-1459,0.0,0.0,1.0,224.0,1
1,1125375,2013,2,5,13,1,2013-05-13,EV,20366,EV,...,38,1301,1300-1359,1423,1400-1459,0.0,0.0,1.0,277.0,2
2,118824,1993,3,9,25,6,1993-09-25,UA,19977,UA,...,41,1650,1600-1659,1730,1700-1759,0.0,0.0,1.0,130.0,1
3,634825,1994,4,11,12,6,1994-11-12,HP,19991,HP,...,81,1245,1200-1259,1457,1400-1459,0.0,0.0,1.0,370.0,2
4,1888125,2017,3,8,17,4,2017-08-17,UA,19977,UA,...,82,755,0700-0759,902,0900-0959,0.0,0.0,1.0,692.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26995,821542,2017,1,1,24,2,2017-01-24,DL,19790,DL,...,63,910,0900-0959,1028,1000-1059,0.0,0.0,1.0,297.0,2
26996,1910565,2013,2,6,27,4,2013-06-27,B6,20409,B6,...,74,1320,1300-1359,1612,1600-1659,0.0,0.0,1.0,1562.0,7
26997,9055,2016,3,8,26,5,2016-08-26,AA,19805,AA,...,22,920,0900-0959,1405,1400-1459,0.0,0.0,1.0,1521.0,7
26998,84136,2009,3,8,8,6,2009-08-08,YV,20378,YV,...,82,1139,1100-1159,1217,1200-1259,0.0,0.0,1.0,73.0,1
26999,113029,1993,3,7,17,6,1993-07-17,DL,19790,DL,...,74,615,0600-0659,721,0700-0759,0.0,0.0,1.0,304.0,2

In [29]:
df

,Unnamed: 0,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,...,DestWac,CRSDepTime,DepTimeBlk,CRSArrTime,ArrTimeBlk,Cancelled,Diverted,Flights,Distance,DistanceGroup
0,1295781,1998,2,4,2,4,1998-04-02,AS,19930,AS,...,93,1330,1300-1359,1426,1400-1459,0.0,0.0,1.0,224.0,1
1,1125375,2013,2,5,13,1,2013-05-13,EV,20366,EV,...,38,1301,1300-1359,1423,1400-1459,0.0,0.0,1.0,277.0,2
2,118824,1993,3,9,25,6,1993-09-25,UA,19977,UA,...,41,1650,1600-1659,1730,1700-1759,0.0,0.0,1.0,130.0,1
3,634825,1994,4,11,12,6,1994-11-12,HP,19991,HP,...,81,1245,1200-1259,1457,1400-1459,0.0,0.0,1.0,370.0,2
4,1888125,2017,3,8,17,4,2017-08-17,UA,19977,UA,...,82,755,0700-0759,902,0900-0959,0.0,0.0,1.0,692.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26995,821542,2017,1,1,24,2,2017-01-24,DL,19790,DL,...,63,910,0900-0959,1028,1000-1059,0.0,0.0,1.0,297.0,2
26996,1910565,2013,2,6,27,4,2013-06-27,B6,20409,B6,...,74,1320,1300-1359,1612,1600-1659,0.0,0.0,1.0,1562.0,7
26997,9055,2016,3,8,26,5,2016-08-26,AA,19805,AA,...,22,920,0900-0959,1405,1400-1459,0.0,0.0,1.0,1521.0,7
26998,84136,2009,3,8,8,6,2009-08-08,YV,20378,YV,...,82,1139,1100-1159,1217,1200-1259,0.0,0.0,1.0,73.0,1
26999,113029,1993,3,7,17,6,1993-07-17,DL,19790,DL,...,74,615,0600-0659,721,0700-0759,0.0,0.0,1.0,304.0,2

In [31]:
df = pd.read_csv('/content/drive/MyDrive/airline_data.csv')
df

,Unnamed: 0,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,...,Div4WheelsOff,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum
0,1295781,1998,2,4,2,4,1998-04-02,AS,19930,AS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1125375,2013,2,5,13,1,2013-05-13,EV,20366,EV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,118824,1993,3,9,25,6,1993-09-25,UA,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,634825,1994,4,11,12,6,1994-11-12,HP,19991,HP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1888125,2017,3,8,17,4,2017-08-17,UA,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26995,821542,2017,1,1,24,2,2017-01-24,DL,19790,DL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26996,1910565,2013,2,6,27,4,2013-06-27,B6,20409,B6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26997,9055,2016,3,8,26,5,2016-08-26,AA,19805,AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26998,84136,2009,3,8,8,6,2009-08-08,YV,20378,YV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26999,113029,1993,3,7,17,6,1993-07-17,DL,19790,DL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
line_data = df.groupby('Month')['ArrDelay'].mean().reset_index()

In [33]:
line_data

    Month  ArrDelay
0       1  7.097321
1       2  6.530025
2       3  5.429533
3       4  4.040055
4       5  5.874889
5       6  9.347515
6       7  8.851436
7       8  7.402630
8       9  2.198975
9      10  3.242506
10     11  4.228961
11     12  9.474149

In [41]:
fig = go.Figure(data=go.Scatter(x=line_data['Month'],y=line_data['ArrDelay'],mode='lines', marker=dict(color='green')))
fig.update_layout(title='Monthly average delayof flights', xaxis_title='Months',yaxis_title='Delay of flight arrival(in minutes)')
fig.show()

In [40]:
import matplotlib.pyplot as plt
fig =pr.pie(df, names='DistanceGroup',title='Monthly Distance group propotion travelled')
#plt.savefig("")
fig.show()